services:
  postgres:
    image: postgres:16
    container_name: e-courier-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ecourier_app
      POSTGRES_PASSWORD: ecourier_app_db_pass
      POSTGRES_DB: ecourier_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
