
server:
  port: 8080

spring:
  application:
    name: ecourier-api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
        - id: parcel-service
          uri: lb://parcel-service
          predicates:
            - Path=/api/parcels/**
        - id: tracking-service
          uri: lb://tracking-service
          predicates:
            - Path=/api/tracking/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
