server:
  port: 9090

spring:
  application:
    name: ecourier-api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin
#        - AddResponseHeader=Access-Control-Allow-Origin, *
#        - AddResponseHeader=Access-Control-Allow-Methods, GET,POST,PUT,DELETE,OPTIONS
#        - AddResponseHeader=Access-Control-Allow-Headers, Content-Type,Authorization
      routes:
        - id: user-service
          uri: lb://ecourier-user-service
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: parcel-service
          uri: lb://ecourier-parcel-service
          predicates:
            - Path=/api/parcels/**
          filters:
            - RemoveRequestHeader=Cookie
        - id: tracking-service
          uri: lb://ecourier-tracking-service
          predicates:
            - Path=/api/tracking/**
          filters:
            - RemoveRequestHeader=Cookie

      httpclient:
        connect-timeout: 2000
        response-timeout: 10s

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http: TRACE
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.client.discovery: DEBUG
    org.springframework.cloud.client.loadbalancer: DEBUG