spring:
  application:
    name: ecourier-parcel-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/ecourier_db
    username: ecourier_app
    password: ecourier_app_db_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
user:
  service:
    url: http://localhost:8080
logging:
  level:
    org.springframework.security: DEBUG
    com.ecourier.parcelservice.security: DEBUG

jwt:
  secret: "jwt_secret_keyaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"