server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecourier_db
    username: ecourier_app
    password: ecourier_app_db_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: "jwt_secret_keyaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  expiration: 86400000

parcel:
  service:
    url: http://localhost:8081

logging:
  level:
    com.ecourier.trackingservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG