server:
  port: 8888

spring:
  application:
      name: ecourier-configserver-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JPAtekur/config-repo
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka